name: equi_dMRI

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - pip>=20.1.1
  - numpy>=1.18.5
  - cudatoolkit=10.2
  - pytorch==1.5.0
  - pip:
    - git+https://github.com/philip-mueller/equivariant-deep-dmri.git
